apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
<<<<<<< HEAD
=======
    Version: 1.3.2
>>>>>>> billing
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 9080
