apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    version:1.4.3
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 9080
